Никитин Сергей 320 группа ВМК
sergeychur/scraping_hw pull request #10
Opened 2024-03-19 11:49 UTC by dayForJames

@sergeychur, здравствуйте, готов сдать задание

2024-03-19 12:53 UTC, sergeychur commented
> @sergeychur, здравствуйте, готов сдать задание

Привет! Сначала необходимо пройти автоматизированную проверку. Сейчас не проходит: https://github.com/sergeychur/scraping_hw/actions/runs/8343038994/job/22832476694?pr=10

2024-03-21 07:08 UTC, sergeychur commented
Напиши коммент снова, пожалуйста, по готовности

2024-03-21 13:20 UTC, dayForJames commented
@sergeychur, вроде бы прошло
В файлике output.txt записал футболистов, которых надо было найти по их свойствам

2024-04-03 16:07 UTC, sergeychur commented
> @sergeychur, вроде бы прошло В файлике output.txt записал футболистов, которых надо было найти по их свойствам

На всякий случай подчеркну, что проверка снова не проходит. Поэтому пока не проверяю.

2024-04-06 14:08 UTC, dayForJames commented
@sergeychur, я фиксил баг с матчами, щас уже всё нормально, готов сдать

2024-04-07 16:57 UTC, sergeychur requested changes

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +        return domain
Не используешь этот метод и дублируешь тот же код в методе parse.

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +                s = '<span class="mw-headline" id="Текущий_состав">Текущий состав</span>'
Не стоит вот так обрабатывать корнер кейсы. Давай попробуем обобщить. Кажется, что во всех вариантах есть общее слово;)

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +            )
Тут нет необходимости как-то обрезать текст страницы, а потом обрезанную часть страницы парсить снова html парсером, получается лишняя работа. Если хочется как-то ограничить часть страницы для дальнейшего разбора, то можно просто передать  в метод какой-то html элемент, внутри которого дальше будет идти поиск. Если такой возможности нет, то можно передать и корневой элемент.

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +        team_table = data.find("table", {"class": "standard sortable"})
Лучше все же эту таблицу найти по тому условию, что она следует за `span[id="Квалифицировались_в_финальный_турнир"]`. Предложенный тобой селектор сломается, если добавят выше еще одну таблицу с тем же классом (он не выглядит уникальным).

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +            size = 2
Такой способ тоже сломается, если добавят еще таблички сверху.
Лучше найти таблицы, которые следуют за заголовками "Текущий состав", "Недавние вызовы". Так вероятность поломки будет ниже.

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +        name = rows[0].find("div", {"class": "label"}).text.strip().split(" ")
У этого rows[0] есть говорящий класс `'ts_Спортсмен_имя'`. Лучше использовать его на случай каких-то внезапных перестановок.

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +        name = rows[0].find("div", {"class": "label"}).text.strip().split(" ")
Также здесь и далее, где вызываешь `"some string".split(" ")` лучше вызывать split без аргументов, так разделение будет идти по всем подряд стоящим пробельным символам (https://docs.python.org/3/library/stdtypes.html#str.split).

2024-04-07 16:57 UTC, sergeychur commented on css_selector_parser.py
> +        return player_data, []
Получилось очень громоздко. Давай попробуем как-то структурировать этот код (по методам). Также просьба постараться избавиться от обработки корнер-кейсов при подсчете числа игр за сборную (вижу там проверку на всякие "Сборная Каталонии" и прочее). По опыту твоих коллег можно обойтись без этого.

2024-04-07 16:57 UTC, sergeychur commented on scripts/compare_results.py
> +
Давай тут и далее уберем изменения в код, подготавливающий окружение для проверки и осуществляющий эту проверку.
Понятно, что они минорные, но смотреть так сложнее.

2024-04-08 12:38 UTC, dayForJames commented
Понял, поправлю

2024-04-21 18:53 UTC, dayForJames commented
@sergeychur, здравствуйте, исправил, готов сдать

2024-04-22 20:50 UTC, sergeychur commented on scripts/compare_results.py
> +
Не убрано.

2024-04-22 21:11 UTC, sergeychur commented on css_selector_parser.py
> +        name = rows[0].find("div", {"class": "label"}).text.strip().split(" ")
В первом пункте так и ищешь внутри rows[0]. Стало чуть-чуть лучше (рандомные данные в имя-фамилию не положишь, упадет), но от перестановки (или добавления фейкового элемента ) не спасет.

Со split вроде везде, где надо поменял; а вот со strip осталось также, любое добавление пробельного символа приведет к лишним символам в результате.

2024-04-22 21:12 UTC, sergeychur commented on css_selector_parser.py
> +        return player_data, []
Разбить на функции получилось, по содержимому разбитого в отдельных комментариях отпишу.

2024-04-22 21:55 UTC, sergeychur requested changes

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +
`len(cols) < 2` ?

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +            text = text[: len(text) - 1]
В python каждый slice копирует строку, не очень удачное решение.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +        start = DT.datetime(int(year), int(month_num), int(day), 0, 0, 0)
Нет необходимости создавать строку, а затем ее парсить. Можно сразу создать объект datetime.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +        return int(res_height)
Такой подход ведет к копированию строки на каждой итерации.
Наверняка между числом и другими символами разделитель есть.
Ну или можно регулярки попробовать использовать, чтобы число выделить из строки, если по другому никак.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +                national_goals.append(int(goals))
Опять же проще выделить число регуляркой и считать, что 0, если не вышло выделить, чем обрабатывать много частных случаев (если появится новый, то все упадет).

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +                player_data["club_scored"] += int(goals)
Тут то же самое, как и в случае с статистикой по национальной сборной.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +            tables = data.find_all("table", {"class": "wikitable"})
Лучше все же найти следующие за этими элементами таблицы, а не искать все таблицы, если такие элементы есть.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +                        national_matches.append(int(matches))
Снова лишнее копирование строк

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +            national_team_career_ind = len(rows)
Лучше из функции возращать не индексы в какой-то таблице и потом многократно парсить элементы этой таблицы, а парсить один раз и возвращать результаты этого парсинга.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +                        goals = int(goals)
Опять же лучше выделить число по-другому.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +                player_data["club_caps"] += int(matches)
Лишнее копирование строк.

2024-04-22 21:55 UTC, sergeychur commented on css_selector_parser.py
> +            for i in range(len(national_teams)):
Можно только последнюю строчку распарсить (там текущая сборная) и для нее все проверки сделать.

2024-04-24 17:54 UTC, dayForJames commented
@sergeychur, исправил, теперь ищу голы и матчи через re, по поводу timestamp не очень понял, я создаю строку birth_str, чтобы поместить её в информацию об игроке, и не делаю её парсинг для нахождения timestamp'a, поэтому просто немного по-другому переписал, также не очень понял, что надо исправить в ./scripts/compare_results.py, поэтому закомментил проверку, остальное вроде бы исправил

2024-04-28 15:46 UTC, sergeychur commented
> @sergeychur, исправил, теперь ищу голы и матчи через re, по поводу timestamp не очень понял, я создаю строку birth_str, чтобы поместить её в информацию об игроке, и не делаю её парсинг для нахождения timestamp'a, поэтому просто немного по-другому переписал, также не очень понял, что надо исправить в ./scripts/compare_results.py, поэтому закомментил проверку, остальное вроде бы исправил

Общий момент. Просьба указывать что и как исправил в соответствующем обсуждении. Как сейчас приходится по-новой просматривать весь код, чтобы понять, исправлено ли.

Пример как делать на картинке.
![Снимок экрана от 2024-04-28 18-44-55](https://github.com/sergeychur/scraping_hw/assets/33199039/5113ccf1-c7ef-4d9c-8470-31f1d04e5a0c)

2024-04-28 15:50 UTC, sergeychur commented on css_selector_parser.py
> +        start = DT.datetime(int(year), int(month_num), int(day), 0, 0, 0)
Тут я неправильно прочитал, извини)

2024-04-28 15:58 UTC, sergeychur commented on scripts/compare_results.py
> +
Имею в виду, что в диффе не должны быть изменения в код, подготавливающий окружение и осуществляющий проверку, а именно `scripts/compare_results.py`, `scripts/run_test.sh`, `scripts/setup_nginx.sh`, `scripts/wiki_nginx.conf`.
Сейчас, например, вижу такое
![Снимок экрана от 2024-04-28 18-52-31](https://github.com/sergeychur/scraping_hw/assets/33199039/cdea5f52-547f-40fe-9d51-5ba3e0556494)
![Снимок экрана от 2024-04-28 18-54-11](https://github.com/sergeychur/scraping_hw/assets/33199039/e2e65ea9-7ebb-41ba-beaa-b154814c4125)
Верни, пожалуйста, в исходное состояние хотя бы scripts/compare_results.py, чтобы работала проверка. Остальное, если непонятно и это останется единственное замечание, можно не исправлять.

2024-04-28 15:59 UTC, sergeychur commented on css_selector_parser.py
> +        name = rows[0].find("div", {"class": "label"}).text.strip().split(" ")
Все равно не так, как я имел в виду, но твой вариант тоже работает) Пускай, остается так.

2024-04-28 16:02 UTC, sergeychur commented on css_selector_parser.py
> +        name = rows[0].find("div", {"class": "label"}).text.strip().split(" ")
Для понимания, что хотелось, можешь посмотреть реализацию твоего коллеги - https://github.com/greatjudge/scraping_hw/blob/master/scraper/parsers/css_selector_parser.py#L184. Все эти значения можно найти при помощи селекторов и отказаться в принципе от цикла. Так будет значительно более компактно.

2024-04-28 16:14 UTC, sergeychur commented on css_selector_parser.py
> +            for i in range(len(national_teams)):
Вроде бы не исправил. Если я не прав, покажи, пожалуйста, как исправлено.

2024-04-28 16:15 UTC, sergeychur commented on css_selector_parser.py
> +            national_team_career_ind = len(rows)
Тут в  общем-то такой же ответ, как и в https://github.com/sergeychur/scraping_hw/pull/10#discussion_r1582217024, т.е. ладно, но ожидалось по-другому.

2024-04-28 16:26 UTC, sergeychur commented
В коде было довольно много исправлений, поэтому скину 2 балла за эту часть. Ответь, пожалуйста, на последние 2 комментария и поставлю.

2024-04-30 09:35 UTC, dayForJames commented on css_selector_parser.py
> +            for i in range(len(national_teams)):
Теперь беру информацию только из последней строки (строки 306-352)

2024-04-30 09:37 UTC, dayForJames commented on scripts/compare_results.py
> +
Скопировал код compare_results.py из исходного репозитория

2024-04-30 11:39 UTC, sergeychur commented
Принято

2024-04-30 11:39 UTC, closed without merging