Селянкина Екатерина
sergeychur/scraping_hw pull request #14
Opened 2024-04-23 22:37 UTC by seldcat

2024-04-24 13:58 UTC, seldcat commented
[geychur](https://github.com/sergeychur), добрый вечер! Готова сдать задание

2024-04-29 20:05 UTC, sergeychur requested changes
Добротный код парсера, комментарии помогали проверять)

Но к сожалению есть проблемы в результате.
1. Есть дубликаты.
```bash 
(venv) sergey@hp:~/stuff/edu_robot/seldcat$ wc -l result.jsonl; wc -l <(sort result.jsonl | uniq)
683 result.jsonl
606 /dev/fd/63
```
Из-за этого, например, в сборной Украины оказалось 60 игроков.
2. В результате есть игроки, у которых в результате не указана национальная сборная:
```bash 
(venv) sergey@hp:~/stuff/edu_robot/seldcat$ cat result.jsonl | grep null | head -n5
{"url": "https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BB%D0%B0%D0%B8,_%D0%93%D0%B0%D0%B1%D0%BE%D1%80", "name": ["Салаи", "Габор"], "height": 191, "position": "защитник", "current_club": "Лозанна", "national_team": null, "birth": 960494400, "club_caps": 115, "national_caps": 0, "club_conceded": 0, "club_scored": 21, "national_conceded": 0, "national_scored": 0}
{"url": "https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%8D%D0%BD%D0%B0,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81", "name": ["Баэна", "Алекс"], "height": 174, "position": "полузащитник", "current_club": "Вильярреал", "national_team": null, "birth": 995572800, "club_caps": 128, "national_caps": 0, "club_conceded": 0, "club_scored": 12, "national_conceded": 0, "national_scored": 0}
{"url": "https://ru.wikipedia.org/wiki/%D0%A5%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D1%81%D0%B5%D0%BD,_%D0%9C%D0%B0%D0%B4%D1%81", "name": ["Хермансен", "Мадс"], "height": 185, "position": "вратарь", "current_club": "Лестер Сити", "national_team": null, "birth": 963259200, "club_caps": 76, "national_caps": 0, "club_conceded": 98, "club_scored": 0, "national_conceded": 0, "national_scored": 0}
{"url": "https://ru.wikipedia.org/wiki/%D0%93%D1%8F%D1%81%D1%83%D0%BB%D1%8F,_%D0%9A%D0%BB%D0%B0%D1%83%D1%81", "name": ["Гясуля", "Клаус"], "height": null, "position": "полузащитник", "current_club": "Дармштадт 98", "national_team": "Сборная Албании по футболу", "birth": 629586000, "club_caps": 367, "national_caps": 27, "club_conceded": 0, "club_scored": 19, "national_conceded": 0, "national_scored": 0}
{"url": "https://ru.wikipedia.org/wiki/%D0%93%D0%B2%D0%B5%D0%BB%D0%B5%D1%81%D0%B8%D0%B0%D0%BD%D0%B8,_%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9", "name": ["Гвелесиани", "Георгий"], "height": 192, "position": "защитник", "current_club": "Персеполис", "national_team": null, "birth": 673390800, "club_caps": 226, "national_caps": 0, "club_conceded": 0, "club_scored": 29, "national_conceded": 0, "national_scored": 0} 
```

Скорее всего так получилось для игроков, которые еще не играли за сборную, но были вызваны на ближайшие матчи типа https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BB%D0%B0%D0%B8,_%D0%93%D0%B0%D0%B1%D0%BE%D1%80. Надо было как-то обработать такой вариант.
3. Есть игроки, для которых указана не актуальная сборная (типа сборная Арубы, сборная Турции до 21 года и прочие не европейские или не взрослые сборные).
```bash
(venv) sergey@hp:~/stuff/edu_robot/seldcat$ cat result.jsonl | jq -r ".national_team" | sort | uniq -c
     27 null
     23 Сборная Австрии по футболу
     17 Сборная Албании по футболу
     48 Сборная Англии по футболу
      1 Сборная Арубы по футболу
     22 Сборная Бельгии по футболу
     19 Сборная Венгрии по футболу
     42 Сборная Германии по футболу
     23 Сборная Грузии по футболу
     22 Сборная Дании по футболу
      1 Сборная ДР Конго по футболу
      2 Сборная Ирландии по футболу
     25 Сборная Испании по футболу
     25 Сборная Италии по футболу
     22 Сборная Нидерландов по футболу
     26 Сборная Польши по футболу
     27 Сборная Португалии по футболу
     23 Сборная Румынии по футболу
      1 Сборная Северной Македонии по футболу
     23 Сборная Сербии по футболу
     23 Сборная Словакии по футболу
     23 Сборная Словении по футболу
     25 Сборная Турции по футболу
      1 Сборная Турции по футболу (до 21 года)
     60 Сборная Украины по футболу
     23 Сборная Франции по футболу
     23 Сборная Хорватии по футболу
     40 Сборная Чехии по футболу
     23 Сборная Швейцарии по футболу
     23 Сборная Шотландии по футболу
```

Поэтому могу поставить 8 баллов. Снял по баллу за корректность результата и за код (раз в результате есть неточности, значит и в коде есть проблемы).
Я так понимаю, что до 3 мая еще можно исправлять. Если успеешь, добавлю.

2024-04-29 20:05 UTC, sergeychur commented on parser/parser.py
> +            result['name'] = result['name'][::-1]
Лучше не обрабатывать единичные случаи, а сделать if, который потенциально сработает для большего числа случаев. Например, такое же есть для [Криштиану Роналду](https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B8%D1%88%D1%82%D0%B8%D0%B0%D0%BD%D1%83_%D0%A0%D0%BE%D0%BD%D0%B0%D0%BB%D0%B4%D1%83).
Кажется, сработает такой вариант.
Если есть запятая в строке с именем и фамилией, то оставляем порядок как есть; иначе меняем порядок на обратный.

2024-04-29 20:05 UTC, sergeychur commented on parser/parser.py
> +                return th.find_next_sibling('td').text.strip()
Тоже можно через `[data-wikidata-property-id="P54"]` найти.

2024-04-29 20:05 UTC, sergeychur commented on runner/simple_runner.py
> +        ]
Это не должно быть нужно. Значит, где-то есть недоработка в коде парсера, раз он возвращает такой урл на следующую обработку.
Раннер только управляет процессом, он ничего не должен знать о конкретном сайте, который мы обкачиваем.

2024-04-29 20:05 UTC, sergeychur commented on parser/parser.py
> +            return 'player'
Если тут как-то проверить, что страница именно игрока, то блэклист и отбрасывание .svg урлов в раннере не нужно.

2024-05-02 22:16 UTC, seldcat commented
@sergeychu готова сдать

2024-05-03 08:07 UTC, seldcat commented on parser/parser.py
> +            return 'player'
svg урлы я видела только в тесте на гитхабе(селекторы локально все правильно находили в тестовых данных). Так что предполагаю, что они появлялись в качестве "ошибки прогрузки файлов", добавила их в код на всякий случай, если предположение неверное. 

Сейчас игрок детектится с помощью характерного только ему карточки футболиста, так отсеиваются капитан и несуществующие страницы игроков(index.php которые). Все это делается в чойсе

svg урлы убрала)

2024-05-03 08:14 UTC, seldcat commented
В итоге стала прокидывать информацию о национальной сборной игрока из самой сборной, для этого в item добавила поле доп информации. Как итог, ушли null и странные сборные

2024-05-03 08:16 UTC, sergeychur commented on scripts/run.sh
> +wget --recursive -w 0.1 -D localhost $seed_url || true
Эта была заглушка вместо вашего кода)

2024-05-03 08:17 UTC, sergeychur commented
Все исправлено. 10 баллов) С заглушкой не страшно.

2024-05-03 08:17 UTC, closed without merging