Дремин Михаил
sergeychur/scraping_hw pull request #15
Opened 2024-04-24 00:21 UTC by dreminm

2024-04-24 00:57 UTC, dreminm commented
[real_result.jsonl.txt](https://github.com/sergeychur/scraping_hw/files/15084575/real_result.jsonl.txt)

2024-04-29 21:10 UTC, sergeychur requested changes
Код в целом добротный. Классно, что использовал библиотечный RateLimiter. 
Есть одно замечание в обсуждениях.
Результат, к сожалению, неполный, там не оказалось сборной Хорватии по футболу.

Пока могу поставить 8 баллов. Насколько понимаю, можно исправить до 3 мая.

2024-04-29 21:10 UTC, sergeychur commented on pageparser.py
> +        self.national_teams = dict()
Парсер не должен хранить такого рода состояние, это не его зона ответственности. Он должен лишь принимать html страницу на вход и отдавать некий структурированный результат на выход без побочных эффектов, влияющих на другие его вызовы.

2024-04-29 21:10 UTC, sergeychur commented on pageparser.py
> +        self.national_teams.update(next_urls)
Тут скорее всего из-за того, что обходишь все ссылки вообще с проверкой, теряешь сборную Хорватии.
Может лучше отобрать по таблице вышедших на евро?

2024-05-04 10:35 UTC, closed without merging