Борисов Иван
sergeychur/scraping_hw pull request #6
Opened 2024-02-26 10:47 UTC by BoogieQQ

2024-02-28 18:03 UTC, sergeychur requested changes
Привет! Круто, что сдаешь работу в первых рядах. Также спасибо за исправление ошибок в задании.

2024-02-28 18:03 UTC, sergeychur commented on main.py
> +    runner.run()
Давай попробуем поиграться с раннером. В коде семинара есть многопоточная и асинхронная реализации, которые уменьшат время выполнения программы. Выбери одну из них и замени на нее SimpleRunner.
Также давай повысим рейт и увеличим число ретраев.

2024-02-28 18:03 UTC, sergeychur commented on result.jsonl
> +{"url": "https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BF%D0%BF,_%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD", "name": ["Трапп", "Кевин"], "height": 189, "position": "вратарь", "current_club": "Айнтрахт (Фр
Почему-то в результатах нет сборной Англии. Также для игрока "Криштиану Роналду" не распарсилась число вызовов в национальную сборную.

2024-02-28 18:03 UTC, sergeychur commented on runner/css_parser.py
> +        for table in tables:
Лучше взять таблицы, которые в секциях "Текущий состав" и "Недавние вызовы" а не перебирать все (их может быть много). Например можно найти нужный h* (у него соответствующий id и потом найти sibling таблицу). Тогда кстати проверка на заголовки не нужна)

2024-02-28 18:03 UTC, sergeychur commented on runner/css_parser.py
> +
Вместо цикла по колонкам таблицы лучше явно использовать соответствие индекса колонки и данных, которые хочешь оттуда достать. Все равно в цикле ифом проверяешь индекс.
И при конструировании объекта Player явно эти параметры передавать.

2024-02-28 18:03 UTC, sergeychur commented on runner/css_parser.py
> +        height = root.find('span', {'data-wikidata-property-id': 'P2048'}).text[:3]
Тут парсишь табличку с данными по игроку, которая находится справа. Лучше сначала найти ее рутовый элемент ```table[data-name="Футболист"]``` и делать следующие запросы внутри нее. Так парсеру придется обходить меньше элементов.

2024-02-28 18:03 UTC, sergeychur commented on runner/css_parser.py
> +        for tr in tr_tags:
Элементов ```tr``` может быть много) Лучше сначала найти таблицу, из которой хотим достать данные (по аналогии со страницей команды), а потом уже ее обработать.

2024-02-28 18:03 UTC, sergeychur commented on runner/footbal_player.py
> +        if player.name[1] == 'Жота':
Нестандартно имя в википедии записали)
Лучше сделать if, который потенциально сработает для большего числа случаев. Например, такое же есть для [Криштиану Роналду](https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B8%D1%88%D1%82%D0%B8%D0%B0%D0%BD%D1%83_%D0%A0%D0%BE%D0%BD%D0%B0%D0%BB%D0%B4%D1%83).
Кажется, сработает такой вариант. 
Если есть запятая в строке с именем и фамилией, то оставляем порядок как есть; иначе меняем порядок на обратный.

2024-02-28 18:09 UTC, sergeychur commented on main.py
> +    runner.run()
Приведи, пожалуйста, еще время работы программы для SimpleRunner и для выбранного тобой варианта.

2024-03-06 15:54 UTC, BoogieQQ commented on runner/css_parser.py
> +        for table in tables:
готово

2024-03-06 15:55 UTC, BoogieQQ commented on runner/css_parser.py
> +
готово?

2024-03-06 15:55 UTC, BoogieQQ commented on runner/css_parser.py
> +        height = root.find('span', {'data-wikidata-property-id': 'P2048'}).text[:3]
готово

2024-03-06 15:55 UTC, BoogieQQ commented on runner/css_parser.py
> +        for tr in tr_tags:
готово

2024-03-06 15:58 UTC, BoogieQQ commented on runner/footbal_player.py
> +        if player.name[1] == 'Жота':
Не помогло: Трапп, Кевин перейдет в Кевин Трапп, что неверное по тестам

2024-03-06 17:00 UTC, BoogieQQ commented on main.py
> +    runner.run()
Результаты:
SimpleRunner(rate=1000, max_tries=5):
	Total time: 186.937s
	46.97s user 1.26s system 25% cpu 3:07.19 total
AsyncRunner(rate=1000, max_parallel=8, max_tries=5):
	Total time: 57.732s
	 36.96s user 0.68s system 64% cpu 58.066 total

2024-03-06 20:38 UTC, sergeychur commented on result.jsonl
> +{"url": "https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BF%D0%BF,_%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD", "name": ["Трапп", "Кевин"], "height": 189, "position": "вратарь", "current_club": "Айнтрахт (Фр
На странице 21 сборная. В результатах 17. Чего-то не докачалось.
```bash
cat result.jsonl | jq -r ".national_team" | sort | uniq
Сборная Австрии по футболу
Сборная Албании по футболу
Сборная Англии по футболу
Сборная Бельгии по футболу
Сборная Венгрии по футболу
Сборная Германии по футболу
Сборная Испании по футболу
Сборная Италии по футболу
Сборная Нидерландов по футболу
Сборная Португалии по футболу
Сборная Румынии по футболу
Сборная Словакии по футболу
Сборная Словении по футболу
Сборная Турции по футболу
Сборная Франции по футболу
Сборная Чехии по футболу
Сборная Шотландии по футболу
```

Нет Дании, Швейцарии, Сербии, Хорватии. Проверь, пожалуйста, парсинг начальной страницы.

2024-03-06 20:56 UTC, sergeychur commented on runner/footbal_player.py
> +        if player.name[1] == 'Жота':
Почему перейдет? Есть запятая, значит останется как есть, то есть ['Трапп', 'Кевин'].
```python
def get_result(title):
    name_cand_arr = title.split(',')
    if len(name_cand_arr) != 2:
        name_cand_arr = [*reversed(title.split())]
    return [*map(lambda x: x.strip(), name_cand_arr)]

>>> get_result('Трапп, Кевин')
['Трапп', 'Кевин']
>>> get_result('Кевин Трапп')
['Трапп', 'Кевин']
```

2024-03-06 21:17 UTC, sergeychur commented on runner/css_parser.py
> +
Не совсем. Тут в общем-то достаточно только ссылку достать. Остальное можно со страницы игрока получится забрать.
Тогда будет так.
```python
# tr уже получили; это элемент, отвечающий за строку в таблице.
link = tr.select_one('td:nth-child(3) > a')
# нужная ссылка - link['href'].
```
Если очень хочется тут еще что-то достать (но вообще не зачем), то можно аналогичным селектором достать.
В общем, я к тому, что цикл выглядит громоздко и тут не нужен.

2024-03-07 06:17 UTC, BoogieQQ commented on result.jsonl
> +{"url": "https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BF%D0%BF,_%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD", "name": ["Трапп", "Кевин"], "height": 189, "position": "вратарь", "current_club": "Айнтрахт (Фр
Поправил

2024-03-07 06:17 UTC, BoogieQQ commented on runner/css_parser.py
> +
Да, достаточно удобно, спасибо

2024-03-07 06:18 UTC, BoogieQQ commented on runner/footbal_player.py
> +        if player.name[1] == 'Жота':
Извиняюсь, в прошлый раз перепутал условия для перестановки — поправил

2024-03-07 10:54 UTC, sergeychur commented
Принято.

2024-03-07 10:54 UTC, closed without merging