Пшеничный Тимофей
sergeychur/scraping_hw pull request #9
Opened 2024-03-03 05:58 UTC by Knispel2

2024-03-07 07:06 UTC, Knispel2 commented
Файлы с результатами:

[result_new.jsonl.txt](https://github.com/sergeychur/scraping_hw/files/14520100/result_new.jsonl.txt)
[stats_ans.txt](https://github.com/sergeychur/scraping_hw/files/14520101/stats_ans.txt)

2024-03-07 07:08 UTC, Knispel2 commented
@sergeychur, здравствуйте, я готов

2024-03-07 15:45 UTC, sergeychur commented
> Файлы с результатами:
> 
> [result_new.jsonl.txt](https://github.com/sergeychur/scraping_hw/files/14520100/result_new.jsonl.txt) [stats_ans.txt](https://github.com/sergeychur/scraping_hw/files/14520101/stats_ans.txt)

В результат пролезли сборные, не участвующие в ЧЕ.
```bash
cat result_new.jsonl.txt | jq -r ".national_team" | sort | uniq -c
18 Сборная Албании по футболу
      1 Молодёжная сборная Бельгии по футболу
      1 Молодёжная сборная Сербии по футболу
      1 Молодёжная сборная Шотландии по футболу
      1 Олимпийская сборная Бельгии по футболу (страница отсутствует)
      1 Олимпийская сборная Португалии по футболу (страница отсутствует)
      1 Олимпийская сборная Хорватии по футболу (страница отсутствует)
      1 Сборная Англии по футболу (до 21 года)
      1 Сборная Германии по футболу (до 21 года)
      1 Сборная Дании по футболу (до 21 года)
      1 Сборная Испании по футболу (до 19 лет)
      1 Сборная Италии по футболу (до 20 лет)
      1 Сборная Нидерландов по футболу (до 19 лет)
      1 Сборная Португалии по футболу (до 21 года)
      1 Сборная Словении по футболу (до 21 года)
      1 Сборная Страны Басков по футболу
      1 Сборная Турции по футболу (до 21 года)
      1 Сборная Хорватии по футболу (до 21 года)
      1 Сборная Чехии по футболу (до 21 года)
      1 Сборная Швейцарии по футболу (до 21 года)
     20 Сборная Венгрии по футболу
     20 Сборная Чехии по футболу
     21 Сборная Бельгии по футболу
     21 Сборная Португалии по футболу
     22 Сборная Дании по футболу
     22 Сборная Испании по футболу
     22 Сборная Румынии по футболу
     22 Сборная Словении по футболу
     22 Сборная Шотландии по футболу
     23 Сборная Австрии по футболу
     23 Сборная Италии по футболу
     23 Сборная Словакии по футболу
     23 Сборная Турции по футболу
     23 Сборная Франции по футболу
     23 Сборная Хорватии по футболу
     23 Сборная Швейцарии по футболу
     24 Сборная Англии по футболу
     25 Сборная Сербии по футболу
     27 null
     27 Сборная Нидерландов по футболу
      2 Молодёжная сборная Германии по футболу
      2 Сборная Нидерландов по футболу (до 21 года)
      3 Сборная Италии по футболу (до 21 года)
     44 Сборная Германии по футболу
```

2024-03-07 15:47 UTC, sergeychur requested changes

2024-03-07 15:47 UTC, sergeychur commented on main.py
> +        runner = AsyncRunner(parser, sink, logger, seed_urls, rate=1, max_tries=5, max_parallel=5)
А почему рейт 1? По идее настройки nginx из теста позволяют 10. Если впритык не проходит, можно чуть понизить (8?). Но 1 - это мало, давай попробуем повысить.

2024-03-07 15:47 UTC, sergeychur commented on parsers/css_selector_parser.py
> +        tables = page_data.select('table.wikitable')
Лучше не обходить все таблицы, которых может быть много, а сразу выбрать лишь нужные.
Например можно найти элементы "Текущий состав" и "Недавние вызовы" и потом найти sibling таблицы.

2024-03-07 15:47 UTC, sergeychur commented on parsers/css_selector_parser.py
> +        team_signature_eng = ['№', 'Позиция', 'Игрок', 'Дата рождения / возраст', 'Игры', 'Голы', 'Клуб']
Если найти только нужные таблицы, то проверка не нужна. Порядок элементов в строчке одинаковый.

2024-03-07 15:47 UTC, sergeychur commented on parsers/css_selector_parser.py
> +                continue
Тоже можно конкретные таблицы найти, а не обходить все.

2024-03-07 15:47 UTC, sergeychur commented on parsers/css_selector_parser.py
> +        utc_seconds = date_object.timestamp()
Кажется, проще разбить на элементы - число, месяц, год (разделить по пробелу); месяц перевести в порядковый номер (по маппингу названия месяца в порядковый номер) и просто создать объект date. Сейчас есть лишние действия.

2024-03-07 15:47 UTC, sergeychur commented on parsers/css_selector_parser.py
> +            raise self._logger.error(f'Не найдена позиция для {url}')
logger.error вернет None. 
```python
>>> raise None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```
По итогу реальная ошибка не будет обработана, и не получится узнать в чем проблема.
Надо поправить здесь и везде далее по коду.

2024-03-07 15:47 UTC, sergeychur commented on runners/simple_runner.py
Этот файл не нужен

2024-03-07 15:47 UTC, sergeychur commented on .idea/misc.xml
.idea файлы лучше не добавлять, у каждого могут быть свои предпочтения по настройке IDE.

2024-03-21 08:55 UTC, Knispel2 commented
> > Файлы с результатами:
> > [result_new.jsonl.txt](https://github.com/sergeychur/scraping_hw/files/14520100/result_new.jsonl.txt) [stats_ans.txt](https://github.com/sergeychur/scraping_hw/files/14520101/stats_ans.txt)
> 
> В результат пролезли сборные, не участвующие в ЧЕ.
> 
> ```shell
> cat result_new.jsonl.txt | jq -r ".national_team" | sort | uniq -c
> 18 Сборная Албании по футболу
>       1 Молодёжная сборная Бельгии по футболу
>       1 Молодёжная сборная Сербии по футболу
>       1 Молодёжная сборная Шотландии по футболу
>       1 Олимпийская сборная Бельгии по футболу (страница отсутствует)
>       1 Олимпийская сборная Португалии по футболу (страница отсутствует)
>       1 Олимпийская сборная Хорватии по футболу (страница отсутствует)
>       1 Сборная Англии по футболу (до 21 года)
>       1 Сборная Германии по футболу (до 21 года)
>       1 Сборная Дании по футболу (до 21 года)
>       1 Сборная Испании по футболу (до 19 лет)
>       1 Сборная Италии по футболу (до 20 лет)
>       1 Сборная Нидерландов по футболу (до 19 лет)
>       1 Сборная Португалии по футболу (до 21 года)
>       1 Сборная Словении по футболу (до 21 года)
>       1 Сборная Страны Басков по футболу
>       1 Сборная Турции по футболу (до 21 года)
>       1 Сборная Хорватии по футболу (до 21 года)
>       1 Сборная Чехии по футболу (до 21 года)
>       1 Сборная Швейцарии по футболу (до 21 года)
>      20 Сборная Венгрии по футболу
>      20 Сборная Чехии по футболу
>      21 Сборная Бельгии по футболу
>      21 Сборная Португалии по футболу
>      22 Сборная Дании по футболу
>      22 Сборная Испании по футболу
>      22 Сборная Румынии по футболу
>      22 Сборная Словении по футболу
>      22 Сборная Шотландии по футболу
>      23 Сборная Австрии по футболу
>      23 Сборная Италии по футболу
>      23 Сборная Словакии по футболу
>      23 Сборная Турции по футболу
>      23 Сборная Франции по футболу
>      23 Сборная Хорватии по футболу
>      23 Сборная Швейцарии по футболу
>      24 Сборная Англии по футболу
>      25 Сборная Сербии по футболу
>      27 null
>      27 Сборная Нидерландов по футболу
>       2 Молодёжная сборная Германии по футболу
>       2 Сборная Нидерландов по футболу (до 21 года)
>       3 Сборная Италии по футболу (до 21 года)
>      44 Сборная Германии по футболу
> ```
[result_new.jsonl.txt](https://github.com/sergeychur/scraping_hw/files/14692453/result_new.jsonl.txt)
Поправил. В основных таблицах некоторых игроков были устаревшие данные об их отношении к сборной, стал брать название сборной из названия страницы команды, на которой этого игрока нашёл

2024-03-21 08:55 UTC, Knispel2 commented on main.py
> +        runner = AsyncRunner(parser, sink, logger, seed_urls, rate=1, max_tries=5, max_parallel=5)
Выше 3 повысить не получается. Не могу сообразить, в чём дело

2024-03-21 08:55 UTC, Knispel2 commented on parsers/css_selector_parser.py
> +        tables = page_data.select('table.wikitable')
Сделал

2024-03-21 08:56 UTC, Knispel2 commented on parsers/css_selector_parser.py
> +        team_signature_eng = ['№', 'Позиция', 'Игрок', 'Дата рождения / возраст', 'Игры', 'Голы', 'Клуб']
Поправил

2024-03-21 08:56 UTC, Knispel2 commented on parsers/css_selector_parser.py
> +                continue
Готово

2024-03-21 08:59 UTC, Knispel2 commented on parsers/css_selector_parser.py
> +        utc_seconds = date_object.timestamp()
Поправил, теперь так:
```python
months_translation = {
            "января": 1,
            "февраля": 2,
            "марта": 3,
            "апреля": 4,
            "мая": 5,
            "июня": 6,
            "июля": 7,
            "августа": 8,
            "сентября": 9,
            "октября": 10,
            "ноября": 11,
            "декабря": 12
        }
        row = probe_el.find_parent('tr')
        age = row.select('span.nowrap a')
        date = ' '.join([obj.text for obj in age[:2]])
        date_list = date.split()
        date_list[1] = months_translation[date_list[1]]
        day, month, year = date_list
        utc_seconds = datetime(int(year), month, int(day)).timestamp()
        result['birth'] = int(utc_seconds)
```

2024-03-21 09:00 UTC, Knispel2 commented on runners/simple_runner.py
Удалил

2024-03-21 09:00 UTC, Knispel2 commented on .idea/misc.xml
Удалил

2024-03-21 09:06 UTC, Knispel2 commented on main.py
> +        runner = AsyncRunner(parser, sink, logger, seed_urls, rate=1, max_tries=5, max_parallel=5)
Даже при rate==3 на некоторых страницах в тесте вылезает 429, и иногда check не проходится. Надежно проходится только при rate==2

2024-03-21 09:06 UTC, Knispel2 commented on parsers/css_selector_parser.py
> +            raise self._logger.error(f'Не найдена позиция для {url}')
Поправил

2024-03-21 09:59 UTC, Knispel2 commented
@sergeychur, насколько критично, что тесты проходятся только с малым rate?

2024-03-26 12:43 UTC, sergeychur commented on parsers/css_selector_parser.py
> +            raise self._logger.error(f'Не найдена позиция для {url}')
Обычно прям базовый Exception не бросают, а бросают наследников, чтобы можно было понимать что случилось не только по сообщению. Но можно не исправлять)

2024-03-26 12:50 UTC, sergeychur commented on parsers/css_selector_parser.py
> +                continue
Честно сказать не понял, что поменялось. Все равно идет поиск всех элементов tbody и проверка каждого из них в цикле. Надо найти таблицы типа таких https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BF%D0%BF,_%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD#%D0%9A%D0%BB%D1%83%D0%B1%D0%BD%D0%B0%D1%8F и https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BF%D0%BF,_%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD#%D0%9C%D0%B0%D1%82%D1%87%D0%B8_%D0%B7%D0%B0_%D1%81%D0%B1%D0%BE%D1%80%D0%BD%D1%83%D1%8E. И далее парсить только их. Поиск можно вести тем же способом с сиблингами, как и при парсинге страницы сборной.

2024-03-26 12:52 UTC, sergeychur commented
> @sergeychur, насколько критично, что тесты проходятся только с малым rate?
> 
> rate limiter брал из семинарских материалов, и вроде всё работает как надо. Не могу понять, где у меня косяк



> ```shell
> cat result_new.jsonl.txt | jq -r ".national_team" | sort | uniq -c
> ```

Теперь вроде хорошо.

2024-03-26 13:35 UTC, sergeychur commented
> @sergeychur, насколько критично, что тесты проходятся только с малым rate?
> 
> rate limiter брал из семинарских материалов, и вроде всё работает как надо. Не могу понять, где у меня косяк

Вероятно я на семинаре поторопился и накосячил в реализации RateLimiter.
Вот такая реализация работает.
```python
def get_delay(self, now=None):
        with self._lock:
            if now is None:
                now = time.time()
            expected_next_call_ts = max(self._last_called_ts + self._delta, now)
            self._last_called_ts = expected_next_call_ts
            return max(expected_next_call_ts - now, 0)
```
Просьба поменять и убедиться.
Ну и не надо, полуачется, все на веру принимать)

2024-03-26 13:36 UTC, sergeychur commented on main.py
> +        runner = AsyncRunner(parser, sink, logger, seed_urls, rate=1, max_tries=5, max_parallel=5)
Отписал в комменте ниже в чем проблема, просьба поменять и проверить.

2024-03-28 18:14 UTC, Knispel2 commented on main.py
> +        runner = AsyncRunner(parser, sink, logger, seed_urls, rate=1, max_tries=5, max_parallel=5)
Спасибо, это помогло

2024-03-28 18:15 UTC, Knispel2 commented on parsers/css_selector_parser.py
> +                continue
Похоже, проглядел этот момент. Сейчас точно исправил

2024-03-28 21:21 UTC, sergeychur commented
Принято

2024-03-28 21:21 UTC, closed without merging